# Generated by Django 5.1.1 on 2024-12-01 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_producto_precio_sin_igv_alter_producto_imagen_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='cliente',
            field=models.CharField(default='Cliente', max_length=200),
        ),
    ]
