# Generated by Django 5.1.1 on 2024-11-28 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_factura_subtotal_alter_factura_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidos',
            name='igv',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='pedidos',
            name='subtotal',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='pedidos',
            name='cantidad',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
